package main

import (
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/ahnara/antifake/backend/pkg/crypto"
	"github.com/ahnara/antifake/backend/pkg/db"
	"github.com/ahnara/antifake/backend/pkg/middleware"
	"github.com/ahnara/antifake/backend/pkg/models"
)

type VerifyReq struct {
	SessionToken string `json:"session_token"` // generated by auth-service after OTP confirmation
	DeviceID     string `json:"device_id"`
	IPCountry    string `json:"ip_country"`
}

type VerificationResponse struct {
	Verdict     string         `json:"verdict"` // genuine, previously_verified, suspicious, highrisk, invalid, recalled
	RiskScore   float64        `json:"risk_score"`
	SessionID   int            `json:"session_id"`
	QRCode      models.QRCode  `json:"qr_code,omitempty"`
	Product     models.Product `json:"product,omitempty"`
	Batch       models.Batch   `json:"batch,omitempty"`
	BrandName   string         `json:"brand_name,omitempty"`
	BrandLogo   string         `json:"brand_logo_url,omitempty"`
}

func main() {
	db.InitDB()
	defer db.DB.Close()

	mux := http.NewServeMux()

	// Public routes
	mux.HandleFunc("/api/verify/token/", handleVerifyToken)

	log.Println("Verification Service starting on port 8083...")
	log.Fatal(http.ListenAndServe(":8083", middleware.CORS(mux)))
}

func handleVerifyToken(w http.ResponseWriter, r *http.Request) {
	// Path: /api/verify/token/{token} or /api/verify/token/{token}/check
	parts := strings.Split(r.URL.Path, "/")
	if len(parts) < 5 {
		http.Error(w, `{"error": "Invalid path"}`, http.StatusBadRequest)
		return
	}

	token := parts[4]

	// Determine if we are just fetching info (GET) or executing the verification check (POST)
	if r.Method == http.MethodGet {
		fetchTokenMetadata(w, token)
		return
	} else if r.Method == http.MethodPost && len(parts) >= 6 && parts[5] == "check" {
		executeVerificationCheck(w, r, token)
		return
	}

	http.Error(w, `{"error": "Method not allowed"}`, http.StatusMethodNotAllowed)
}

func fetchTokenMetadata(w http.ResponseWriter, token string) {
	// Query token and product details so consumer landing page can load details before verification
	var q models.QRCode
	var p models.Product
	var b models.Batch
	var brandName string
	var brandLogo sql.NullString
	var desc, img sql.NullString

	query := `SELECT q.id, q.batch_id, q.token, q.signature, q.status, 
	                 b.id, b.product_id, b.batch_code, b.quantity, b.manufacture_date, b.expiry_date, b.status,
	                 p.id, p.producer_id, p.name, p.sku, p.category, p.description, p.image_url,
	                 pr.name, pr.brand_logo_url
			  FROM qr_codes q
			  JOIN batches b ON q.batch_id = b.id
			  JOIN products p ON b.product_id = p.id
			  JOIN producers pr ON p.producer_id = pr.id
			  WHERE q.token = ?`

	err := db.DB.QueryRow(query, token).Scan(
		&q.ID, &q.BatchID, &q.Token, &q.Signature, &q.Status,
		&b.ID, &b.ProductID, &b.BatchCode, &b.Quantity, &b.ManufactureDate, &b.ExpiryDate, &b.Status,
		&p.ID, &p.ProducerID, &p.Name, &p.SKU, &p.Category, &desc, &img,
		&brandName, &brandLogo,
	)

	p.Description = desc.String
	p.ImageURL = img.String

	if err == sql.ErrNoRows {
		// Return dummy invalid details instead of 404 to avoid breaking landing page template
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(VerificationResponse{
			Verdict:   "invalid",
			RiskScore: 1.0,
		})
		return
	} else if err != nil {
		log.Printf("Database error in fetchTokenMetadata: %v", err)
		http.Error(w, `{"error": "Database error"}`, http.StatusInternalServerError)
		return
	}

	// Validate signature to confirm authenticity
	if !crypto.VerifyTokenSignature(q.Token, q.Signature) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(VerificationResponse{
			Verdict:   "invalid",
			RiskScore: 1.0,
			QRCode:    q,
			Product:   p,
			Batch:     b,
			BrandName: brandName,
			BrandLogo: brandLogo.String,
		})
		return
	}

	// Check if batch is recalled
	if b.Status == models.StatusRecalled {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(VerificationResponse{
			Verdict:   "recalled",
			RiskScore: 1.0,
			QRCode:    q,
			Product:   p,
			Batch:     b,
			BrandName: brandName,
			BrandLogo: brandLogo.String,
		})
		return
	}

	// Return active metadata
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(VerificationResponse{
		Verdict:   "pending_otp",
		QRCode:    q,
		Product:   p,
		Batch:     b,
		BrandName: brandName,
		BrandLogo: brandLogo.String,
	})
}

func executeVerificationCheck(w http.ResponseWriter, r *http.Request, token string) {
	var req VerifyReq
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, `{"error": "Invalid request"}`, http.StatusBadRequest)
		return
	}

	if req.SessionToken == "" {
		http.Error(w, `{"error": "Session token required (consumer OTP not verified)"}`, http.StatusBadRequest)
		return
	}

	// 1. Verify consumer session token signature (token|phone|timestamp . signature)
	parts := strings.Split(req.SessionToken, ".")
	if len(parts) != 2 {
		http.Error(w, `{"error": "Invalid session token format"}`, http.StatusBadRequest)
		return
	}
	payload, clientSig := parts[0], parts[1]
	expectedSig := crypto.SignToken(payload)
	if expectedSig != clientSig {
		http.Error(w, `{"error": "Session token signature verification failed"}`, http.StatusForbidden)
		return
	}

	// Extract details from payload
	payloadParts := strings.Split(payload, "|")
	if len(payloadParts) < 3 {
		http.Error(w, `{"error": "Invalid session payload"}`, http.StatusBadRequest)
		return
	}
	sessionTokenVal, phone := payloadParts[0], payloadParts[1]
	if sessionTokenVal != token {
		http.Error(w, `{"error": "Session token mismatch"}`, http.StatusBadRequest)
		return
	}

	// 2. Fetch QR code details
	var q models.QRCode
	var p models.Product
	var b models.Batch
	var brandName string
	var brandLogo sql.NullString
	var desc, img sql.NullString

	query := `SELECT q.id, q.batch_id, q.token, q.signature, q.status, 
	                 b.id, b.product_id, b.batch_code, b.quantity, b.manufacture_date, b.expiry_date, b.status,
	                 p.id, p.producer_id, p.name, p.sku, p.category, p.description, p.image_url,
	                 pr.name, pr.brand_logo_url
			  FROM qr_codes q
			  JOIN batches b ON q.batch_id = b.id
			  JOIN products p ON b.product_id = p.id
			  JOIN producers pr ON p.producer_id = pr.id
			  WHERE q.token = ?`

	err := db.DB.QueryRow(query, token).Scan(
		&q.ID, &q.BatchID, &q.Token, &q.Signature, &q.Status,
		&b.ID, &b.ProductID, &b.BatchCode, &b.Quantity, &b.ManufactureDate, &b.ExpiryDate, &b.Status,
		&p.ID, &p.ProducerID, &p.Name, &p.SKU, &p.Category, &desc, &img,
		&brandName, &brandLogo,
	)
	p.Description = desc.String
	p.ImageURL = img.String

	if err == sql.ErrNoRows {
		// Unknown QR
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(VerificationResponse{Verdict: "invalid", RiskScore: 1.0})
		return
	} else if err != nil {
		http.Error(w, `{"error": "Database error"}`, http.StatusInternalServerError)
		return
	}

	// 3. Begin risk analysis (default genuine)
	riskScore := 0.0
	verdict := "genuine"
	var signals []string

	// Check cryptographic integrity
	if !crypto.VerifyTokenSignature(q.Token, q.Signature) {
		riskScore = 1.0
		verdict = "invalid"
		signals = append(signals, "tampered_token")
	}

	// Check if batch is recalled
	if b.Status == models.StatusRecalled {
		riskScore = 1.0
		verdict = "recalled"
	}

	// Check scan history if cryptographic check passes
	if verdict != "invalid" && verdict != "recalled" {
		phoneHash := hashString(phone)

		// Create/Get consumer details
		var consumerID int
		err = db.DB.QueryRow(`SELECT id FROM consumers WHERE phone_number_hash = ?`, phoneHash).Scan(&consumerID)
		if err == sql.ErrNoRows {
			res, _ := db.DB.Exec(`INSERT INTO consumers (phone_number_hash, verification_count, created_at) VALUES (?, 1, ?)`, phoneHash, time.Now())
			cid, _ := res.LastInsertId()
			if cid == 0 {
				db.DB.QueryRow(`SELECT id FROM consumers WHERE phone_number_hash = ?`, phoneHash).Scan(&consumerID)
			} else {
				consumerID = int(cid)
			}
		} else {
			consumerID = int(consumerID)
			db.DB.Exec(`UPDATE consumers SET verification_count = verification_count + 1 WHERE id = ?`, consumerID)
		}

		// Count previous scans of this specific QR token
		var prevScansCount int
		db.DB.QueryRow(`SELECT COUNT(*) FROM verification_sessions WHERE qr_code_id = ?`, q.ID).Scan(&prevScansCount)

		if prevScansCount > 0 {
			// Scan repeated! Check signals
			verdict = "previously_verified"
			
			// Signal 1: Device fingerprint mismatch
			var lastDeviceID string
			db.DB.QueryRow(`SELECT device_id FROM verification_sessions WHERE qr_code_id = ? ORDER BY created_at DESC LIMIT 1`, q.ID).Scan(&lastDeviceID)
			if lastDeviceID != "" && lastDeviceID != req.DeviceID {
				riskScore += 0.35 // Medium weight
				signals = append(signals, "device_mismatch")
			}

			// Signal 2: Different phone numbers scanning same QR
			var uniquePhones int
			db.DB.QueryRow(`SELECT COUNT(DISTINCT consumer_id) FROM verification_sessions WHERE qr_code_id = ?`, q.ID).Scan(&uniquePhones)
			if uniquePhones > 1 {
				riskScore += 0.45 // High weight
				signals = append(signals, "different_phone_reused")
			}

			// Signal 3: Scan velocity (scanned too fast consecutively)
			var lastScanTime time.Time
			db.DB.QueryRow(`SELECT created_at FROM verification_sessions WHERE qr_code_id = ? ORDER BY created_at DESC LIMIT 1`, q.ID).Scan(&lastScanTime)
			if !lastScanTime.IsZero() && time.Since(lastScanTime) < 5*time.Minute {
				riskScore += 0.25 // Medium weight
				signals = append(signals, "multiple_scans_short_period")
			}
		}

		// Cap risk score at 1.0
		if riskScore > 1.0 {
			riskScore = 1.0
		}

		// Determine final verdict based on aggregated risk
		if riskScore >= 0.7 {
			verdict = "highrisk"
		} else if riskScore >= 0.3 {
			verdict = "suspicious"
		}

		// 4. Log the verification session in database
		tx, err := db.DB.Begin()
		if err != nil {
			http.Error(w, `{"error": "DB transaction failure"}`, http.StatusInternalServerError)
			return
		}
		defer tx.Rollback()

		var sessionID int64
		res, err := tx.Exec(`INSERT INTO verification_sessions (qr_code_id, consumer_id, device_id, ip_country, result, risk_score, created_at)
			VALUES (?, ?, ?, ?, ?, ?, ?)`,
			q.ID, consumerID, req.DeviceID, req.IPCountry, verdict, riskScore, time.Now())
		if err == nil {
			sessionID, _ = res.LastInsertId()
		}

		// 5. Create Fraud Events for flagged runs
		if len(signals) > 0 {
			for _, sigType := range signals {
				severity := "medium"
				if riskScore >= 0.7 {
					severity = "high"
				}
				tx.Exec(`INSERT INTO fraud_events (verification_session_id, signal_type, severity, created_at)
					VALUES (?, ?, ?, ?)`, sessionID, sigType, severity, time.Now())
			}
		}

		tx.Commit()

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(VerificationResponse{
			Verdict:   verdict,
			RiskScore: riskScore,
			SessionID: int(sessionID),
			QRCode:    q,
			Product:   p,
			Batch:     b,
			BrandName: brandName,
			BrandLogo: brandLogo.String,
		})
		return
	}

	// Recalled or Invalid directly returns without logging consumer session
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(VerificationResponse{
		Verdict:   verdict,
		RiskScore: riskScore,
		QRCode:    q,
		Product:   p,
		Batch:     b,
		BrandName: brandName,
		BrandLogo: brandLogo.String,
	})
}

func hashString(val string) string {
	h := sha256.New()
	h.Write([]byte(val))
	return hex.EncodeToString(h.Sum(nil))
}
