// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {printer} from '../models';

export function CheckForUpdates(arg1:string):Promise<main.UpdateInfo>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GeneratePrintSheetLocal(arg1:printer.PrintConfig,arg2:Array<string>,arg3:string):Promise<void>;

export function SelectSavePath(arg1:string,arg2:string):Promise<string>;
