// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function GeneratePrintSheetLocal(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePrintSheetLocal'](arg1, arg2, arg3);
}

export function SelectSavePath(arg1, arg2) {
  return window['go']['main']['App']['SelectSavePath'](arg1, arg2);
}
